### ISSUE TITLE
Help Wanted.

### ISSUE THREAD

**Issue by kashyap-shah** [clubgamma/Awesome-Web-Art#28]
# Hello Club Gamma!
I have made Snake Game, Weather Forecast App, etc and also making to-do list using html, css and Javascript.
Can you suggest me what to do or where to commit pull-request for this projects.
Also wanna ask that can I add my social media links, because I have already add them in footer of my projects

**Comment by yashpaneliya** [comment]
Hello @kashyap-shah ,

It looks like you have done great work with HTML,CSS and JS. You can showcase your work in our repo.
To submit a PR, go through the steps written in [CONTRIBUTING.md](https://github.com/clubgamma/Awesome-Web-Art/blob/master/CONTRIBUTING.md).

You can embed your social media link in your webpage that you are going to submit.

We will be very happy to see your contribution☺
